CICD: Add switching to save build results after success build

diff --git a/build_script b/build_script
--- a/build_script
+++ b/build_script
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# To save build results put "NotDelBuildResults" as commandline parameter of this script !!!
+
 #MultiLineBashCommenter() {
 
 [ -z $BASH ] || shopt -s expand_aliases
@@ -41,8 +43,17 @@ fi
 PreviousCommandExitCodeCheck() {
 
 if [ $? -ne 0 ]; then
-  echo -e "Failure: execute previous command\n" >&2
+  echo -e "PreviousCommandExitCodeCheck: Failure execute previous command\n" >&2
   exit 1
+fi
+
+}
+
+CheckNotDelBuildCommandLineArgument() {
+
+if [[ "$1" == "NotDelBuildResults" ]]; then
+  echo -e "$1: Save all build results\n";
+  exit 0
 fi
 
 }
@@ -65,5 +76,7 @@ if [ -f build/html2pdf ]; then
       mkdir html2pdf
       cp build/html2pdf html2pdf/
 fi
+
+CheckNotDelBuildCommandLineArgument $1
 
 DeleteTmpBildFolders
